### ISSUE TITLE
installation broken

### ISSUE THREAD

**Issue by ebuchman** [davebryson/py-tendermint#1]
using `python3 setup.py install`

Need this diff to get it to work:

```
-        'rlp>=0.6.0',
-        'trie>=0.2.4',
+        'rlp==0.4.7',
+        'trie==0.2.4',
```

**Comment by davebryson** [comment]
Thanks Ethan!   Will check this out

**Comment by davebryson** [comment]
Fixed.  Thanks Ethan!
Also removed the embedded abci core library.  This now relies on the pip version of py-abci
